
CREATE TABLE IF NOT EXISTS users(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    birthday DATE NOT NULL,
    login VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT users_pk PRIMARY KEY(user_id)
);

CREATE TABLE IF NOT EXISTS friendship(
    user_id INTEGER REFERENCES users,
    friend_id INTEGER REFERENCES users
);

CREATE TABLE IF NOT EXISTS mpa(
    rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_name varchar(10) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS films(
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    description varchar(200) NOT NULL,
    duration INTEGER NOT NULL,
    release_date DATE NOT NULL,
    rating_id INTEGER REFERENCES mpa,
    CONSTRAINT films_pk PRIMARY KEY(film_id),
    CONSTRAINT release_date_chk CHEK (release_date >= "1895-12-28")
);

CREATE TABLE IF NOT EXISTS genre(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film_genre(
    film_id INTEGER REFERENCES films,
    genre_id INTEGER REFERENCES genre
);

CREATE TABLE IF NOT EXISTS likes(
    film_id INTEGER REFERENCES films,
    user_id INTEGER REFERENCES users
);